#!/bin/bash
#PBS -j oe
#PBS -m ae
#PBS -N trim_reads
#PBS -M alexander.macadam@my.jcu.edu.au
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=16:mem=350gb

cd $PBS_O_WORKDIR

# Add this to all of your scripts
shopt -s expand_aliases
source /etc/profile.d/modules.sh
 
# Output some useful info
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"

# Set the path to trimmomatic.jar
TRIMMOMATIC_JAR="/home/jc828813/RNAseq/qc2/Trimmomatic-0.39/trimmomatic-0.39.jar"

# Set the path to the adapters file
ADAPTERS="/home/jc828813/RNAseq/qc2/adapters/TruSeq3-PE.fa"

# Loop through all forward reads in the raw_reads folder
for infile in *_R1_001.fastq.gz
 do
   base=$(basename ${infile} _R1_001.fastq.gz)
   java -jar "$TRIMMOMATIC_JAR" PE ${infile} ${base}_R2_001.fastq.gz \
                ${base}_R1_001.trim.fastq.gz ${base}_R1_001un.trim.fastq.gz \
                ${base}_R2_001.trim.fastq.gz ${base}_R2_001un.trim.fastq.gz \
                ILLUMINACLIP:"$ADAPTERS":2:30:10:2:True LEADING:3 TRAILING:3 MINLEN:30 
 done