---
title: "06.7_extract_aten_juvenile_symb_WildDtre_gene_counts"
output: html_document
date: "2024-05-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
#set working directory
setwd("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA")
```

```{r}
#load count data
Juveniles_Wild_Plate3_A5_S215_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_A5_S215_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_A7_S231_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_A7_S231_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_A8_S239_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_A8_S239_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_B4_S208_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_B4_S208_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_B6_S224_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_B6_S224_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_C1_S185_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_C1_S185_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_C3_S201_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_C3_S201_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_C4_S209_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_C4_S209_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_C5_S217_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_C5_S217_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_D5_S218_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_D5_S218_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_D6_S226_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_D6_S226_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_D7_S234_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_D7_S234_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_E5_S219_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_E5_S219_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_E7_S235_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_E7_S235_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_F3_S204_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_F3_S204_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_F5_S220_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_F5_S220_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_F6_S228_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_F6_S228_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_G4_S213_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_G4_S213_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_G5_S221_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_G5_S221_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_G6_S229_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_G6_S229_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_G7_S237_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_G7_S237_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_H4_S214_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_H4_S214_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_H6_S230_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_H6_S230_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
Juveniles_Wild_Plate3_H7_S238_aten<-read.table("/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/aten_juveniles/symbiont/Wild_Dtre/Plate3_H7_S238_unmapped_host_mapped_to_Wild_Dtre_ReadsPerGene.out.tab", sep="\t", header=FALSE)
```

```{r}
input_data_frames1<- c("Juveniles_Wild_Plate3_A5_S215_aten",
"Juveniles_Wild_Plate3_A7_S231_aten",
"Juveniles_Wild_Plate3_A8_S239_aten",
"Juveniles_Wild_Plate3_B4_S208_aten",
"Juveniles_Wild_Plate3_B6_S224_aten",
"Juveniles_Wild_Plate3_C1_S185_aten",
"Juveniles_Wild_Plate3_C3_S201_aten",
"Juveniles_Wild_Plate3_C4_S209_aten",
"Juveniles_Wild_Plate3_C5_S217_aten",
"Juveniles_Wild_Plate3_D5_S218_aten",
"Juveniles_Wild_Plate3_D6_S226_aten",
"Juveniles_Wild_Plate3_D7_S234_aten",
"Juveniles_Wild_Plate3_E5_S219_aten",
"Juveniles_Wild_Plate3_E7_S235_aten",
"Juveniles_Wild_Plate3_F3_S204_aten",
"Juveniles_Wild_Plate3_F5_S220_aten",
"Juveniles_Wild_Plate3_F6_S228_aten",
"Juveniles_Wild_Plate3_G4_S213_aten",
"Juveniles_Wild_Plate3_G5_S221_aten",
"Juveniles_Wild_Plate3_G6_S229_aten",
"Juveniles_Wild_Plate3_G7_S237_aten",
"Juveniles_Wild_Plate3_H4_S214_aten",
"Juveniles_Wild_Plate3_H6_S230_aten",
"Juveniles_Wild_Plate3_H7_S238_aten")
```

```{r}
input_data_frames2<- c("Juveniles_Wild_Plate3_A5_S215_aten_2",
"Juveniles_Wild_Plate3_A7_S231_aten_2",
"Juveniles_Wild_Plate3_A8_S239_aten_2",
"Juveniles_Wild_Plate3_B4_S208_aten_2",
"Juveniles_Wild_Plate3_B6_S224_aten_2",
"Juveniles_Wild_Plate3_C1_S185_aten_2",
"Juveniles_Wild_Plate3_C3_S201_aten_2",
"Juveniles_Wild_Plate3_C4_S209_aten_2",
"Juveniles_Wild_Plate3_C5_S217_aten_2",
"Juveniles_Wild_Plate3_D5_S218_aten_2",
"Juveniles_Wild_Plate3_D6_S226_aten_2",
"Juveniles_Wild_Plate3_D7_S234_aten_2",
"Juveniles_Wild_Plate3_E5_S219_aten_2",
"Juveniles_Wild_Plate3_E7_S235_aten_2",
"Juveniles_Wild_Plate3_F3_S204_aten_2",
"Juveniles_Wild_Plate3_F5_S220_aten_2",
"Juveniles_Wild_Plate3_F6_S228_aten_2",
"Juveniles_Wild_Plate3_G4_S213_aten_2",
"Juveniles_Wild_Plate3_G5_S221_aten_2",
"Juveniles_Wild_Plate3_G6_S229_aten_2",
"Juveniles_Wild_Plate3_G7_S237_aten_2",
"Juveniles_Wild_Plate3_H4_S214_aten_2",
"Juveniles_Wild_Plate3_H6_S230_aten_2",
"Juveniles_Wild_Plate3_H7_S238_aten_2")
```

```{r}
# Loop through each input data frame
for (df_name in input_data_frames1) {
  # Create the new data frame by removing rows 1 to 4 from the original data frame
  new_df_name <- paste0(df_name, "_2")  # Construct the new data frame name
  assign(new_df_name, get(df_name)[-c(1, 2, 3, 4), , drop = FALSE])
}
```

```{r}
#save gene names
genes<-Juveniles_Wild_Plate3_A5_S215_aten |>
  select(V1)

genes<- genes |> rename(genes = V1)

genes<-  genes[-c(1, 2, 3, 4),]
```

```{r}
rm("Juveniles_Wild_Plate3_A5_S215_aten",
"Juveniles_Wild_Plate3_A7_S231_aten",
"Juveniles_Wild_Plate3_A8_S239_aten",
"Juveniles_Wild_Plate3_B4_S208_aten",
"Juveniles_Wild_Plate3_B6_S224_aten",
"Juveniles_Wild_Plate3_C1_S185_aten",
"Juveniles_Wild_Plate3_C3_S201_aten",
"Juveniles_Wild_Plate3_C4_S209_aten",
"Juveniles_Wild_Plate3_C5_S217_aten",
"Juveniles_Wild_Plate3_D5_S218_aten",
"Juveniles_Wild_Plate3_D6_S226_aten",
"Juveniles_Wild_Plate3_D7_S234_aten",
"Juveniles_Wild_Plate3_E5_S219_aten",
"Juveniles_Wild_Plate3_E7_S235_aten",
"Juveniles_Wild_Plate3_F3_S204_aten",
"Juveniles_Wild_Plate3_F5_S220_aten",
"Juveniles_Wild_Plate3_F6_S228_aten",
"Juveniles_Wild_Plate3_G4_S213_aten",
"Juveniles_Wild_Plate3_G5_S221_aten",
"Juveniles_Wild_Plate3_G6_S229_aten",
"Juveniles_Wild_Plate3_G7_S237_aten",
"Juveniles_Wild_Plate3_H4_S214_aten",
"Juveniles_Wild_Plate3_H6_S230_aten",
"Juveniles_Wild_Plate3_H7_S238_aten")
```

```{r}
# Loop through each input data frame
for (df_name in input_data_frames2) {
  # Select only column V2 in each data frame
  assign(df_name, get(df_name) %>%
           select(V2))
}
```

```{r}
# Loop through each input data frame
for (df_name in input_data_frames2) {
  # Extract column name from the data frame name
  col_name <- gsub("_\\d+$", "", df_name)  # Remove the trailing "_2" from the data frame name
  
  # Rename column V2 to the data frame name in each data frame
  assign(df_name, get(df_name) %>%
           rename(!!col_name := V2))
}
```

```{r}
#bind sample counts together
count_table <- genes |>
cbind(Juveniles_Wild_Plate3_A5_S215_aten_2) |>
cbind(Juveniles_Wild_Plate3_A7_S231_aten_2) |>
cbind(Juveniles_Wild_Plate3_A8_S239_aten_2) |>
cbind(Juveniles_Wild_Plate3_B4_S208_aten_2) |>
cbind(Juveniles_Wild_Plate3_B6_S224_aten_2) |>
cbind(Juveniles_Wild_Plate3_C1_S185_aten_2) |>
cbind(Juveniles_Wild_Plate3_C3_S201_aten_2) |>
cbind(Juveniles_Wild_Plate3_C4_S209_aten_2) |>
cbind(Juveniles_Wild_Plate3_C5_S217_aten_2) |>
cbind(Juveniles_Wild_Plate3_D5_S218_aten_2) |>
cbind(Juveniles_Wild_Plate3_D6_S226_aten_2) |>
cbind(Juveniles_Wild_Plate3_D7_S234_aten_2) |>
cbind(Juveniles_Wild_Plate3_E5_S219_aten_2) |>
cbind(Juveniles_Wild_Plate3_E7_S235_aten_2) |>
cbind(Juveniles_Wild_Plate3_F3_S204_aten_2) |>
cbind(Juveniles_Wild_Plate3_F5_S220_aten_2) |>
cbind(Juveniles_Wild_Plate3_F6_S228_aten_2) |>
cbind(Juveniles_Wild_Plate3_G4_S213_aten_2) |>
cbind(Juveniles_Wild_Plate3_G5_S221_aten_2) |>
cbind(Juveniles_Wild_Plate3_G6_S229_aten_2) |>
cbind(Juveniles_Wild_Plate3_G7_S237_aten_2) |>
cbind(Juveniles_Wild_Plate3_H4_S214_aten_2) |>
cbind(Juveniles_Wild_Plate3_H6_S230_aten_2) |>
cbind(Juveniles_Wild_Plate3_H7_S238_aten_2)
```

```{r}
#write out count table
write_tsv(count_table, "/Users/alexmacadam/Library/CloudStorage/Dropbox/PhD/Chapter4_RNA/Data/Gene_counts/count_tables/Juvenile_symbiont/aten_juveniles_symb_WildDtre_counts.tsv")
```
