#!/bin/bash
#PBS -V
#PBS -m ae
#PBS -N 10.1_aten_juv_rCCA
#PBS -M alexander.macadam@my.jcu.edu.au
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=16:mem=150gb
#PBS -o 10.1_aten_juv_rCCA.log
#PBS -e 10.1_aten_juv_rCCA.err

cd $PBS_O_WORKDIR

#make sure you are in wd: /home/jc828813/RNAseq

# Add this to all of your scripts
shopt -s expand_aliases
source /etc/profile.d/modules.sh
 
# Output some useful info
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"

# Load the container we want to use
# It is a good idea to always specify the version number
module load R

 cd /home/jc828813/RNAseq/scripts

Rscript 10.1_aten_juv_rCCA.R